theme: jekyll-theme-tactile
title: punctuationmarks' github page
description: Here is an overview of what I've been working on lately and what interests me, regarding computer science
notes: Just testing out what else can be put into this yaml file
bots: do_not_track
